%CompileKStats.m

%Loads in mat files for k-values and compiles them into long format.
%  Matlab files should be pre-computed from 'VoxelDemingSlopeMapStuff.m'
%  and are named 'V%X_sigmaFac_Y'  where X is the visual area ('V1, V2 or
%  V3)' and Y is the sigma scale factor (1, 2 or 3).  Should be run separately for each
% combination of visual area and sigma scale factor.
%
% results are save in 'allk.csv' with fields{'sub','rad','ROI','sigma','k'};
%
% Plots of k vs. eccentricity (figures 5 and 6 in the scotoma paper) are
% generated by 'MakeScotomaFigures.m' in the ../text/scotoma/matlab'
% directory.

% hard-coded 3x3 list of ROI's and sigma scaling factors.
ROIList = [1,2,3];
sigmaList = 1:3;


sub = {};
ROI = {};
sigma = {};
k = [];
rad = [];


load V1_sigmaFac_1.mat

[radList,subList] = meshgrid(radX,1:10);

for ROINum = 1:length(ROIList)
    for sigmaNum = 1:length(sigmaList)
        fileName = sprintf('V%d_sigmaFac_%d',ROIList(ROINum),sigmaList(sigmaNum));
        load(fileName);
        for i=1:length(radList(:));
            sub = [sub,sprintf('sub%02d',subList(i))];
            ROI = [ROI,sprintf('V%d',ROIList(ROINum))];
            sigma = [sigma,sprintf('sigma%d',sigmaList(sigmaNum))];
         
            rad = [rad,radList(i)];
        end
        k = [k,bestFill(:)'];
    end
end

T = table(sub',rad',ROI',sigma',k');
T.Properties.VariableNames = {'sub','rad','ROI','sigma','k'};

writetable(T,'allk.csv')


%% 
% sanity check, make a plot of k vs eccentricity.

M = xls2struct('allk.csv');
x = radX;
sigma = 'sigma3';
ROI = 'V3';

M.rad = [M.rad{:}]';
M.k = [M.k{:}]';

radList = unique(M.rad);

%radList = radList(radList<=2.1);

m = zeros(size(radList));
sem = zeros(size(radList));

y = zeros(10,length(radList));

for radNum = 1:length(radList);

id = strcmp(M.ROI,ROI) & strcmp(M.sigma,sigma) & M.rad == radList(radNum);
    m(radNum) = mean(M.k(id));
    sem(radNum) = std(M.k(id))/sqrt(sum(id));
    y(:,radNum) = M.k(id);
end

figure(1)
clf
hold on
patch([2,2.4,2.4,2],[-.1,-.1,1.1,1.1],[.8,.8,.8],'LineStyle','none');


for i=1:length(radList)
    plot(radList(i),y(:,i),'k.')
    plot((radList(i)+.1)*[1,1],[-.1,1.1],'k-','Color',[.9,.9,.9])
end

errorbar(radList,m,sem,'k','LineStyle','none')
plot(radList,m,'ko-','MarkerFaceColor','k','MarkerSize',5)

set(gca,'YLim',[-.1,1.1])
plot([0,2.4],[0,0],'k:')
xlabel('Eccentricity (deg)')
ylabel('Filling In Factor (k)');
text(0.1,1,ROI,'FontSize',16,'HorizontalAlignment','center')
set(gca,'XLim',[0,2.4])
set(gca,'XTick',[0:.2:2.4])