%MakeScotomaFigures.m
% Generates figure for the 'scotoma' paper.
%
% Data for Figures 2, 3 and 4 (example pRFs) are derived from the raw data,
% which  sits in C:\Users\Geoff Boynton\Documents\MATLAB\scotoma\Kelly_thesis_scotoma
% and is first compiled into structures subjectData and stimData.  Once
% compiled it runs much faster, but you should clear all to change the ROI
% or any other paramaters.
%
% Data for figures 5 and 6 (k as a function of eccentricity) are derived
% from pre-computed k-statistics in 'all.csv' which is generated by first
% running 'VoxelDemingSlopeMapStuff.m' which generates

% Details:
%
% Figures 2 and 3: example pRFs, time courses and Deming slopes.  V1, Subject 1,
% Run 1, pRF's closest to xc = [.5,1.75,6.5]/sqrt(2); yc = [.5,1.75,6.5]/sqrt(2);
%
% Figure 2:  Set  simFlag = 0;
% Figure 3:  Set  simFlag = 1;  fillFrac = 0;
% Figure 4:  Set  simFlag = 1;  fillFrac = 0.55;
%
% Figure 5:  Set sigma = 'sigma1';
% Figure 6:  Set sigma  = 'sigma2';


dataDr = 'C:\Users\Geoff Boynton\Documents\MATLAB\scotoma\Kelly_thesis_scotoma';
homeDr = pwd;
addpath(dataDr)
TR = 1.2;

simFlag = 1;  % set to 0 or 1 for real vs. simulated data.
fillFrac = .55;  % Use 0.55 for voxel 2, s = 1, runNum = 1
sigma = 'sigma2';

if ~exist('subjectData','var')
    chdir(dataDr)
    compileOpts.ROI = 1;
    compileOpts.radRange = [0,4];
    compileOpts.minvexpl = 0.2;  %
    compileOpts.minSigma = 0.1;
    compileOpts.subList = 1:10;
    compileOpts.edgeSigma = 0;
    [subjectData,stimData,x,y] = compileStimAndSubData(compileOpts);
    chdir(homeDr);
end

fixSize = 0.25;


cx = cos(linspace(-pi,pi,101));
cy = sin(linspace(-pi,pi,101));
%%

xc = [.5,1.75,6.5]/sqrt(2);
yc = [.5,1.75,6.5]/sqrt(2);

nVox = length(xc);
s = 1;  % subject
runNum  = 1;



%%


opts = struct();
opts.edgeNSigma = 2;
opts.combineRuns = 'concat';
opts.lambda = 1;
opts.forceZeroIntercept = true;
opts.centerData = true;
opts.useVoxelWeights = true;

beta = voxelDemingSlopeMap(subjectData{s}, opts);

%%
% simulated data and slopes
noiseSD = 0;
simData = simulateSubjectDataWithFilling(subjectData(s), stimData, noiseSD, fillFrac, opts);
simBeta = voxelDemingSlopeMap(simData{1}, opts);

cmap = repmat(linspace(1,0,256)',1,3);

figure(1)
clf
set(gcf,'Color','w')

if fillFrac == 0 | simFlag==0
    voxList = 1:3;
else
    voxList = 2;
end



for i=voxList

    d = sqrt((subjectData{s}.prfXY(:,1)-xc(i)).^2 +(subjectData{s}.prfXY(:,2)-yc(i)).^2);

    [foo,id ] = min(d);
    hold on


    subplot(3,3,i*3-2)

    hold on
    G = reshape(subjectData{s}.Gprf(:,id),108,108);

    imagesc(x(1,:),y(:,1),G)

    patch(2*cx,2*cy,[.7,.7,.7],'FaceAlpha',.5);
    plot(8*cx,8*cy,'k-')

    plot(fixSize*[-1,1],[0,0],'r-','LineWidth',2)
    plot([0,0],fixSize*[-1,1],'r-','LineWidth',2)

    colormap(cmap)
    axis equal
    axis tight
    set(gca,'XTick',[-8:4:8])
    set(gca,'YTick',[-8:4:8])
    axis off

    % Time courses
    subplot(3,3,i*3-1)

    hold on


    xx = subjectData{1}.Yfull{runNum}(:,id);
    yy = subjectData{1}.Yscot{runNum}(:,id);
    sx =std(xx);
    sy =std(yy);
    thisBeta = beta(id);
    if simFlag
        simxx = simData{s}.Yfull{runNum}(:,id);
        simyy = simData{s}.Yscot{runNum}(:,id);
        xx = simxx;
        yy = simyy;
        thisBeta = simBeta(id);
    end

    nt = size(xx,1);
    t = TR*(1:nt);

    plot(t,xx,'b-')
    hold on
    plot(t,yy,'k-')
    xlabel('Time (s)')
    if simFlag
        ylabel('Simulated Bold')
    else
        ylabel('BOLD (%)')
    end
    legend({'Full','Scotoma'})

    %%

    subplot(3,3,i*3)



    plot(xx,yy,'.')
    axis equal
    axis square

    if simFlag
        axMax = .5;
        axTicks = [-axMax:.25:axMax];
    else
        axMax = 4;
        axTicks = [-axMax:2:axMax];
    end
    axRange = [-axMax,axMax];


    hold on
    plot(axRange,thisBeta*axRange,'k-');
    set(gca,'XLim',axRange*1.1);
    set(gca,'YLim',axRange*1.1);
    set(gca,'XTick',axTicks)
    set(gca,'YTick',axTicks)
    xlabel('Full')

    if simFlag & fillFrac>0
        ylabel(sprintf('Scotoma + (%g)(Full - Scotoma)',fillFrac));
    else
        ylabel('Scotoma')
    end
    text(0,axMax*.9,sprintf('Deming Slope: %0.2f',thisBeta),'HorizontalAlignment','center','VerticalAlignment','bottom')





end

%%
figure(2)
clf
set(gcf,'Color','w')
hold on

M = xls2struct([dataDr,filesep,'allk.csv']);
M.rad = [M.rad{:}]';
M.k = [M.k{:}]';

ROIList = {'V1','V2','V3'};

colList = [1,0,0;0,1,0;0,0,1];
fontSize = 14;


radList = unique(M.rad);

patch([2,2.4,2.4,2],[-.1,-.1,1.1,1.1],.95*[1,1,1],'LineStyle','none');

for i=1:length(radList)
    % plot(radList(i),y(:,i),'k.','Color',colList(ROINum,:))
    plot((radList(i)+.1)*[1,1],[-.1,1.1],'k-','Color',[.9,.9,.9])
end

h_legend = [];



for ROINum = 1:length(ROIList)
    ROI = ROIList{ROINum};


    %radList = radList(radList<=2.1);

    m = zeros(size(radList));
    sem = zeros(size(radList));

    y = zeros(10,length(radList));
    for radNum = 1:length(radList);

        id = strcmp(M.ROI,ROI) & strcmp(M.sigma,sigma) & M.rad == radList(radNum);

        m(radNum) = mean(M.k(id));
        sem(radNum) = std(M.k(id))/sqrt(sum(id));
        y(:,radNum) = M.k(id);
    end
    errorbar(radList,m,sem,'k','LineStyle','none','Color',colList(ROINum,:))
    h_legend(ROINum) = plot(radList,m,'ko-','Color',colList(ROINum,:),'MarkerFaceColor',colList(ROINum,:),'MarkerSize',8);
end

set(gca,'YLim',[-.15,1.05])
plot([0,2.4],[0,0],'k:')
xlabel('Eccentricity (deg)','FontSize',fontSize)
ylabel('Filling In Factor (k)','FontSize',fontSize);
legend(h_legend,ROIList,'Location','NorthWest')
set(gca,'XLim',[0,2.4])
set(gca,'XTick',[0:.2:2.4])
set(gca,'FontSize',fontSize)


%% Eccentricity at half height

nSubs = length(unique(M.sub));
x= radList;

halfWidth = zeros(nSubs,length(ROIList));

figure(4)
clf
colList = hsv(nSubs+1)
for ROINum = 1:3
    subplot(1,3,ROINum)
    hold on
    for subNum = 1:10
        y = zeros(length(radList),1);
        for radNum = 1:length(radList)

            id = strcmp(M.ROI,ROIList{ROINum}) & strcmp(M.sub,sprintf('sub%0.2d',subNum)) & M.rad == radList(radNum) & strcmp(M.sigma,sigma);
            y(radNum) = M.k(id);



        end
        plot(x,y,'k-','Color',colList(subNum,:))
        
    end
    set(gca,'XLim',[0,2])
end
