% validatePRFPipeline
% Run this inexpensive preflight check before the nonlinear fits. It loads
% the same data as the analysis but does not optimize any model.

requiredFunctions = {'compileStimAndSubData','subData','loadScotomaStimuli', ...
    'loadHRFParams','hrf_twogamma','convHRF','convByHemisphere','fminsearchcon'};
for i = 1:numel(requiredFunctions)
    if exist(requiredFunctions{i},'file') ~= 2
        error('validatePRFPipeline:missingFunction', ...
              'Required function %s is not on the MATLAB path.',requiredFunctions{i});
    end
end

roiList = 1:3;
report = table();
for roi = roiList
    compileOpts = struct('ROI',roi,'radRange',[0 5],'minvexpl',0.2, ...
        'minSigma',0.1,'subList',1:10,'edgeSigma',0);
    [subjectData,stimData,x,y] = compileStimAndSubData(compileOpts);
    for s = 1:numel(subjectData)
        S = subjectData{s}; D = stimData{s};
        nRun = numel(S.Yfull); nVox = size(S.prfXY,1);
        if nRun ~= 3 || numel(S.Yscot) ~= 3 || numel(D.SfullRaw) ~= 3 || ...
                numel(D.SscotRaw) ~= 3
            error('validatePRFPipeline:runCount', ...
                  'V%d subject %d does not contain three matched runs.',roi,S.subNum);
        end
        for r = 1:nRun
            if ~isequal(size(S.Yfull{r}),size(S.Yscot{r})) || ...
                    size(S.Yfull{r},2) ~= nVox || ...
                    size(S.Yfull{r},1) ~= size(D.SfullRaw{r},1) || ...
                    ~isequal(size(D.SfullRaw{r}),size(D.SscotRaw{r})) || ...
                    size(D.SfullRaw{r},2) ~= numel(x)
                error('validatePRFPipeline:dimensionMismatch', ...
                      'V%d subject %d run %d dimensions disagree.',roi,S.subNum,r);
            end
        end
        if any(hypot(S.prfXY(:,1),S.prfXY(:,2)) > 5+10*eps) || ...
                any(S.sigma < 0.1) || any(S.w_vox <= 0.2) || ...
                numel(S.sourceVoxelIndex) ~= nVox || numel(S.hemIdx) ~= nVox
            error('validatePRFPipeline:selectionMismatch', ...
                  'V%d subject %d violates the declared voxel filters.',roi,S.subNum);
        end
        row = table(roi,S.subNum,nVox,nnz(S.hemIdx == 1),nnz(S.hemIdx == 2), ...
            min(hypot(S.prfXY(:,1),S.prfXY(:,2))), ...
            max(hypot(S.prfXY(:,1),S.prfXY(:,2))), ...
            'VariableNames',{'ROI','subject','nVox','nLeft','nRight','minEcc','maxEcc'});
        report = [report;row]; %#ok<AGROW>
    end
end
disp(report)
fprintf('\nPreflight checks passed for %d subject-by-ROI datasets.\n',height(report));
